# This file was autogenerated by Claude on 2025-04-04, and hasn't been validated:

# Create Neovim config directory if it doesn't exist
$nvimConfigPath = "$env:LOCALAPPDATA\nvim"
if (!(Test-Path $nvimConfigPath)) {
    New-Item -ItemType Directory -Force -Path $nvimConfigPath
    Write-Host "Created Neovim config directory at $nvimConfigPath"
}

# Create a simple init.vim file
$initVimPath = "$nvimConfigPath\init.vim"
if (!(Test-Path $initVimPath)) {
    # If you have your custom _vimrc, use this line to source it
    "source ~/code/dotfiles/neovim/_vimrc" | Out-File -FilePath $initVimPath -Encoding utf8
    Write-Host "Created init.vim that sources your custom _vimrc"
} else {
    Write-Host "init.vim already exists at $initVimPath"
}

# For IdeaVim and VSCode compatibility
$ideaVimrcPath = "$env:USERPROFILE\.ideavimrc"
if (!(Test-Path $ideaVimrcPath)) {
    "source ~/code/dotfiles/neovim/_vimrc" | Out-File -FilePath $ideaVimrcPath -Encoding utf8
    Write-Host "Created .ideavimrc at $ideaVimrcPath"
} else {
    Write-Host ".ideavimrc already exists at $ideaVimrcPath"
}

# For VSCodeVim
$vscodekeybindingsPath = "$env:APPDATA\Code\User\keybindings.json"
if (Test-Path $vscodekeybindingsPath) {
    Write-Host "VSCode keybindings.json exists at $vscodekeybindingsPath"
    Write-Host "You may need to edit it manually to add your vim-specific keybindings"
}

Write-Host "Setup complete! Your Neovim is configured to use your existing remappings."
