" For a plugin manager, checkout https://github.com/junegunn/vim-plug
" Cross platform support is wacky, so maybe just use it on unix only

" Behavior Settings
set noerrorbells
set noswapfile
set incsearch
set smartcase
set wrapmargin=4
set encoding=utf-8

" Visual Settings
syntax on
set colorcolumn=80
set number

" Mappings
:let mapleader = " "
:let maplocalleader = "-"
" nnoremap <c-d> dd
" inoremap <c-d> <esc>ddi
inoremap jk <esc>
inoremap <c-u> <esc>viwU<esc>i
nnoremap <c-u> viwU<esc>

" Whitespace stuff
" Default vim settings (?):
" set tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set noexpandtab
set smartindent

" TODO autocmd commands for file types

" Advanced Mappings
nnoremap <leader><tab> :call ShowWhiteSpaceToggle()<cr>
let g:show_white_space = 0

function! ShowWhiteSpaceToggle()
	if g:show_white_space
		let g:show_white_space=0
		set nolist
		set listchars=space:\ ,tab:\	\	
	else
		set listchars=space:_,tab:>~
		set list
		let g:show_white_space=1
	endif
endfunction

" ~~~ Other vim reference ~~~
" ~~ Spacing: ~~
" Show all tabs: /\t
" Show trailing whitespace:/\s\+$
" Show trailing whitespace only after some text (ignores blank lines):
" /\S\zs\s\+$
" Show spaces before a tab:/ \+\ze\t

