" Behavior Settings
set noerrorbells
set noswapfile
set incsearch
set smartcase
set wrapmargin=4
set encoding=utf-8

" Visual Settings
syntax on
set colorcolumn=80
set number

" Mappings
:let mapleader = " "
:let maplocalleader = "-"
" nnoremap <c-d> dd
" inoremap <c-d> <esc>ddi
inoremap jk <esc>
inoremap <c-u> <esc>viwU<esc>i
nnoremap <c-u> viwU<esc>

" Whitespace stuff
" Default vim settings (?):
" set tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set noexpandtab
set smartindent

" Advanced Mappings
nnoremap <leader><tab> :call ShowWhiteSpaceToggle()<cr>
let g:show_white_space = 0

function! ShowWhiteSpaceToggle()
	if g:show_white_space
		let g:show_white_space=0
		set nolist
		set listchars=space:\ ,tab:\	\	
	else
		set listchars=space:_,tab:>~
		set list
		let g:show_white_space=1
	endif
endfunction

" Plugins
