:let mapleader = " "
:let maplocalleader = "-"

set number
set wrapmargin=4

" Is this a thing?:
set encoding=utf-8

" nnoremap <c-d> dd
" inoremap <c-d> <esc>ddi
" inoremap <c-l> <esc><c-l>i
inoremap jk <esc>
inoremap <c-u> <esc>viwU<esc>i
nnoremap <c-u> viwU<esc>

" Whitespace stuff
" Default vim settings (?):
" set tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set noexpandtab

nnoremap <leader><tab> :call ShowWhiteSpaceToggle()<cr>
let g:show_white_space = 0

function! ShowWhiteSpaceToggle()
	if g:show_white_space
		let g:show_white_space=0
		set nolist
		set listchars=space:\ ,tab:\	\	
	else
		set listchars=space:_,tab:>~
		set list
		let g:show_white_space=1
	endif
endfunction

